### ISSUE TITLE
Create a new MongoDB configuration in MongoDB Atlas

### ISSUE THREAD

**Issue by 73nko** [codevsoft/workkit#14]
I think it would be a good idea to have a QA database that can be used for all of us with 2 intentions. 

First of all, we can have shared data to check bugs and issues in an easier way.
Also, frontend developers don't need to run a database instance in our local machine and spend resources.

https://www.mongodb.com/cloud/atlas is a good free option.

Once created the database in the atlas, the data must be shared on slack and each of us could update the .env file to aim to the dev DB or QA db.

**Comment by JaMoLpE88** [comment]
DB created:
`AWS / Frankfurt`
user: `**`
pwd: `**`
role: `Atlas Admin`
`mongodb+srv://<user>:<password>@cluster0.w7ri3.mongodb.net/test `

Login details in Slack.

**Comment by JaMoLpE88** [comment]
Enviroments and README instructions updated. 
Commit: f8a3d4503ee2750e8280337320b0f927241238a9
